### ISSUE TITLE
alloc executable region

### ISSUE THREAD

**Issue by dragokas** [Scags/SM-Memory#1]
Hi,
thanks a lot for a such useful ext !!!

Can I ask you please to add functionality to change the flags of the allocated memory region to be executable?

E.g. this is useful when I would like to insert in code the check like
```
if (x != NULL)
```
I could alloc executable mem with your extension, then I could make a manual detour of some opcode (raw address) inside a function that crashed for me, jump to new executable memory, do a required check, and jump back.

Again, thanks in advance.
And great job!

**Comment by Scags** [comment]
Funny, I had just done that the other day but never pushed. I can upload in a bit, sure.

**Comment by Scags** [comment]
Added with the latest commit and release. I'll leave this open for a while just in case.
