### ISSUE TITLE
After updating to the latest version, my server is getting segmentation faults

### ISSUE THREAD

**Issue by higps** [Scags/SM-Memory#4]
When unloading the extension the segmentation fault stops

https://crash.limetech.org/kc2jlk7ha3ef

**Comment by Scags** [comment]
I got a report of a similar issue. 2 things:

While your server is off.
1. Delete all the dump files in `sourcemod/data/dumps/`
2. Try this updated ext.so instead -> [sm-mem.ext.so.zip](https://github.com/Scags/SM-Memory/files/12476355/sm-mem.ext.so.zip)

Then restart and see if the crashing still continues.

**Comment by higps** [comment]
That solved it, however the extension doesn't load on my production servers that's running ubuntu 18.04

 <FAILED> file "sm-mem.ext.so": /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/tf2server/serverfiles/tf/addons/sourcemod/extensions/sm-mem.ext.so)
 
 While my test server has ubuntu 22.04 and it works just fine there

**Comment by Scags** [comment]
This should be fixed in the latest release. If issues are still continuing feel free to either re-up this issue or file a new one.
